from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
import json

import pandas as pd

from carevalue_claims_ml.agent_contracts import AgentHandoffContract, now_utc_iso, validate_handoff_contract
from carevalue_claims_ml.memory_store import SharedContextStore


@dataclass(frozen=True)
class AgentRecommendation:
    member_id: str
    recommendation: str
    priority: float
    rationale: str


@dataclass(frozen=True)
class AgentGuardrails:
    recommendation_only: bool = True
    max_outreach: int = 200
    vulnerable_member_protection: bool = True
    abstain_low_confidence_below: float = 0.15


def cohort_detection(scored: pd.DataFrame) -> pd.DataFrame:
    out = scored.copy()
    if "score" not in out.columns:
        raise ValueError("Input requires `score` column.")
    out["score"] = out["score"].astype(float)
    out["cohort"] = pd.cut(
        out["score"],
        bins=[-1.0, 0.3, 0.6, 2.0],
        labels=["low_need", "rising_risk", "high_risk"],
    ).astype(str)
    return out


def risk_triage_agent(scored: pd.DataFrame) -> pd.DataFrame:
    out = scored.copy()
    if "uncertainty" not in out.columns:
        out["uncertainty"] = (0.5 - (out["score"].astype(float) - 0.5).abs()).clip(lower=0.0)
    if "dual_status_proxy" not in out.columns:
        out["dual_status_proxy"] = 0
    out["triage_priority"] = out["score"].astype(float)
    # Penalize high uncertainty and upweight vulnerable cohorts.
    out["triage_priority"] = (
        out["triage_priority"]
        - 0.3 * out["uncertainty"].astype(float)
        + 0.05 * out["dual_status_proxy"].astype(float)
    )
    out["triage_bucket"] = pd.cut(
        out["triage_priority"],
        bins=[-1, 0.3, 0.6, 1.1],
        labels=["routine", "watch", "high"],
    )
    return out


def care_gap_agent(triaged: pd.DataFrame) -> pd.DataFrame:
    out = triaged.copy()
    if "uplift_score" not in out.columns:
        out["uplift_score"] = out["score"].astype(float) * 0.7
    if "eligible_for_outreach" not in out.columns:
        out["eligible_for_outreach"] = 1
    out["recommended_action"] = out["triage_bucket"].map(
        {"high": "care_navigation_call", "watch": "pharmacy_followup", "routine": "digital_nudge"}
    ).astype(str)
    out.loc[out["uplift_score"] < 0.2, "recommended_action"] = "abstain_low_uplift"
    out.loc[out["eligible_for_outreach"] == 0, "recommended_action"] = "abstain_not_eligible"
    out["agent_rationale"] = (
        "Generated by riskTriageAgent and careGapAgent using score and triage bucket."
    )
    return out


def contract_impact_agent(recs: pd.DataFrame) -> pd.DataFrame:
    out = recs.copy()
    if "expected_cost" not in out.columns:
        out["expected_cost"] = 300.0 + 200.0 * out["score"].astype(float)
    out["expected_contract_delta"] = 0.05 * out["score"].astype(float) * out["expected_cost"].astype(float)
    out["expected_pmpm_delta"] = out["expected_contract_delta"] / 12.0
    out["shared_savings_impact"] = 0.5 * out["expected_contract_delta"]
    out["provider_advisory_action"] = out["recommended_action"].map(
        {
            "care_navigation_call": "prioritize_complex_care_plan",
            "pharmacy_followup": "medication_review_outreach",
            "digital_nudge": "digital_engagement_campaign",
        }
    ).fillna("manual_review_required")
    out["provider_advisory_rationale"] = (
        "Advisory derived from risk, uplift proxy, and contract impact expectations."
    )
    return out


def data_quality_agent(scored: pd.DataFrame) -> dict[str, float | str]:
    alerts: list[str] = []
    missing_rate = float(scored.isna().mean().mean())
    if missing_rate > 0.1:
        alerts.append("missingness_spike")
    schema_anomaly = 0.0 if {"member_id", "month", "score"}.issubset(scored.columns) else 1.0
    if schema_anomaly > 0:
        alerts.append("schema_anomaly")
    drift_proxy = float((scored["score"].astype(float).mean() - 0.5) if "score" in scored.columns else 0.0)
    if abs(drift_proxy) > 0.25:
        alerts.append("score_distribution_drift")
    return {
        "missing_rate": missing_rate,
        "schema_anomaly": schema_anomaly,
        "drift_proxy": drift_proxy,
        "alerts": ",".join(alerts) if alerts else "none",
    }


def _apply_guardrails(recs: pd.DataFrame, guardrails: AgentGuardrails) -> pd.DataFrame:
    out = recs.sort_values("triage_priority", ascending=False).copy()
    out["autonomous_action_blocked"] = bool(guardrails.recommendation_only)
    out["why_not"] = ""
    out.loc[out["uncertainty"].astype(float) >= (1.0 - guardrails.abstain_low_confidence_below), "recommended_action"] = (
        "abstain_low_confidence"
    )
    out.loc[out["recommended_action"].str.startswith("abstain"), "why_not"] = "guardrail_abstain"
    if guardrails.vulnerable_member_protection:
        out.loc[
            (out["dual_status_proxy"].astype(float) > 0) & (out["recommended_action"] == "digital_nudge"),
            "recommended_action",
        ] = "care_navigation_call"
    if len(out) > guardrails.max_outreach:
        over = out.index[guardrails.max_outreach :]
        out.loc[over, "recommended_action"] = "abstain_budget_cap"
        out.loc[over, "why_not"] = "max_outreach_cap"
    return out


def generate_audit_log(
    recs: pd.DataFrame, quality: dict[str, float | str], output_path: Path | None = None
) -> pd.DataFrame:
    audit = recs[["member_id", "month", "score", "triage_bucket", "recommended_action", "agent_rationale", "why_not"]].copy()
    audit["quality_alerts"] = str(quality.get("alerts", "none"))
    audit["audit_timestamp_utc"] = datetime.now(timezone.utc).isoformat()
    if output_path is not None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        audit.to_csv(output_path, index=False)
    return audit


def run_agentic_pipeline(
    scored: pd.DataFrame,
    guardrails: AgentGuardrails | None = None,
    context_store: SharedContextStore | None = None,
) -> pd.DataFrame:
    active_guardrails = guardrails or AgentGuardrails()
    context = context_store or SharedContextStore()
    cohort_df = cohort_detection(scored)
    quality = data_quality_agent(cohort_df)
    triaged = risk_triage_agent(cohort_df)
    recs = care_gap_agent(triaged)
    impacts = contract_impact_agent(recs)
    bounded = _apply_guardrails(impacts, active_guardrails)
    context.set("latest_quality", quality)
    context.set("latest_guardrails", asdict(active_guardrails))
    context.append_event("quality_gate", {"quality": quality})
    context.append_event("guardrail_application", {"rows": len(bounded)})
    return bounded


def build_handoff_contract(
    stage: str,
    records: pd.DataFrame,
    run_id: str = "manual",
    contract_id: str = "DEMO",
    policy_version: str = "v1",
    upstream_stage_ids: list[str] | None = None,
    quality_status: str = "ok",
) -> AgentHandoffContract:
    payload = records.head(25).to_dict(orient="records")
    contract = AgentHandoffContract(
        stage=stage,
        payload=payload,
        version="v1",
        run_id=run_id,
        contract_id=contract_id,
        policy_version=policy_version,
        upstream_stage_ids=upstream_stage_ids or [],
        quality_status=quality_status,
        generated_at=now_utc_iso(),
    )
    validate_handoff_contract(contract)
    return contract


def write_contract(contract: AgentHandoffContract, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(asdict(contract), indent=2), encoding="utf-8")
